### ISSUE TITLE
Problem opening wallet on Mac OSx

### ISSUE THREAD

**Issue by tommaton** [HTMLCOIN/HTMLCOIN#3]
I seem to be having a problem with opening the 2.0.3 wallet on my Mac. the wallet of which it worked fine the first time on opening but now after filing in the coin swap form I can no longer open it.

I get the following error message:

Error: A fatal internal error occurred, see debug.log for details

And in the debug.log file

2018-01-03 21:49:25 ERROR: ReadBlockFromDisk(CBlock&, CBlockIndex*): GetHash() doesn't match index for CBlockIndex(pprev=0x7f89bdd648c0, nHeight=47734, merkle=e388a6fed8b2086d87d5b2ab9171fd0fa32c8209c860f4669aad0d5d036c399b, hashBlock=135c78706113da025cd36302877729d8873fe3063034fd100ccd53cc99d1f25b) at CBlockDiskPos(nFile=0, nPos=24618334)
2018-01-03 21:49:25 * Failed to read block

Do you have any advice on how I can fix this so I can ensure I have my HTML coins.

Thanks,
Tom

**Comment by NHornburg** [comment]
Looks like you failed in syncing a block.  
1) Make a backup of your wallet.dat file (not sure what it is on mac) move it out its current folder and into a secure place.
1a) Make a copy of your wallet.dat backup file (not sure what it is on mac) move it out its current folder and into a different secure place.
1b) Now Copy the entire folder and place it in a separate secure place.
Reread steps 1-1b and confirm you are backed up.... :-)
2) Delete all the contents of the original folder that contained the wallet.dat
3) Restart the wallet and allow it to re-sync.

If that doesn't work, hit me up on the official Telegram channel: https://t.me/htmlcoinofficial   @Neec0 is me.

**Comment by sahara108** [comment]
I also get the same problem. Tried to do what you said, but it can't connect any peer.

**Comment by Bushstar** [comment]
There's a bug with new clients not being able to connect, try connecting manually with the following command in the debug console using IP addresses from the linked in text document. A new client will be coming out in the next couple of days with this connection issue fixed.

addnode 165.227.147.196 add

https://pastebin.com/VXj0MNqt

**Comment by sahara108** [comment]
addnode work well. Thank @Bushstar

**Comment by Bushstar** [comment]
The 2.0.0.4 client is also out now which should resolve this issue.

https://github.com/HTMLCOIN/HTMLCOIN/releases/tag/v2.0.0.4

**Comment by tommaton** [comment]
@Bushstar where do I run the command `addnode 165.227.147.196 add`

**Comment by sunk818** [comment]
To Help > Debug > Console

run the command inside the Console

**Comment by tommaton** [comment]
@sunk818 thanks for the info, but unfortunately I cant even open the wallet that far, it crashes before that stage.

**Comment by sunk818** [comment]
Start from scratch

If still don't work then run disk first aid to repair drive

**Comment by tommaton** [comment]
After following @NHornburg @sunk818 steps and updating the wallet it now works. Thanks all

**Comment by sunk818** [comment]
Did you start from scratch wallet install, run disk repair, or both?

**Comment by tommaton** [comment]
Start from scratch wallet install
